<?php


/**
 * Implement of hook_menu().
 */
function install_contrib_module_menu() {
  $items = array();

  $items['admin/config/install_contrib_module'] = array(
    'title' => 'Install contrib module Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('install_contrib_module_admin_form'),
    'file' => 'includes/install_contrib_module.admin.inc',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );
  
  return $items;
}