<?php


/**
 * Implement of hook_menu().
 */
function module_sys_menu() {
  $items = array();

  $items['admin/config/module_sys'] = array(
    'title' => 'Module Sys Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('module_sys_admin_form'),
    'file' => 'includes/module_sys.admin.inc',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );
  
  return $items;
}